version: '{build}'
image: Visual Studio 2017
configuration:
- Debug
- Release
- Installer
platform: x86
init:
# Set "build version number" to "short-commit-hash" or when tagged to "tag name"
- ps: >-
    $githash = $($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))

    $buildnumber = $($env:APPVEYOR_BUILD_NUMBER)

    if ($env:APPVEYOR_REPO_TAG -eq "true") {

    Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME).$($buildnumber)-$($githash)"

    } else {

    Update-AppveyorBuild -Version "build$($buildnumber)-$($githash)"

    }
environment:
  INNODIR: C:\Program Files (x86)\Inno Setup 5
install:
- cmd: >-
    set

    git submodule update --init --recursive

    set PATH=%INNODIR%;%PATH%
build:
  project: src\rssavers.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: installer/output/*.exe
  name: installer
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: XLQMxoubqEHl7wgYM1IIYnh4eslkXQOtiU77c8DjHxREq1NEADw3lpxAHQAPAyd6
  artifact: /.*\.exe/
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
    CONFIGURATION: Installer